<!DOCTYPE html><html lang="en-us" >

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.8.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Kumakt">

  
  
  
    
  
  <meta name="description" content="Logistic回帰の実装について簡単に">

  
  <link rel="alternate" hreflang="en-us" href="../../post/logi/">

  


  
  
  
  <meta name="theme-color" content="#3f51b5">
  

  
  
  
  <script src="../../js/mathjax-config.js"></script>
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha256-4w9DunooKSr3MFXHXWyFER38WmPdm361bQS/2KUWZbU=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.css" integrity="sha256-SHMGCYmST46SoyGgo4YR/9AlK1vf3ff84Aq9yK4hdqM=" crossorigin="anonymous">
    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    

  

  
  
  
    
      
      
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CRoboto:400,400italic,700%7CRoboto+Mono&display=swap">
    
  

  
  
  
  
  <link rel="stylesheet" href="../../css/academic.css">

  




  


  
  

  

  <link rel="manifest" href="../../index.webmanifest">
  <link rel="icon" type="image/png" href="../../images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_32x32_fill_lanczos_center_2.png">
  <link rel="apple-touch-icon" type="image/png" href="../../images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_192x192_fill_lanczos_center_2.png">

  <link rel="canonical" href="../../post/logi/">

  
  
  
  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary">
  
  <meta property="og:site_name" content="Kumakt Memorandum">
  <meta property="og:url" content="/post/logi/">
  <meta property="og:title" content="Logistic回帰の実装 | Kumakt Memorandum">
  <meta property="og:description" content="Logistic回帰の実装について簡単に"><meta property="og:image" content="/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_512x512_fill_lanczos_center_2.png">
  <meta property="twitter:image" content="/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_512x512_fill_lanczos_center_2.png"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2020-07-14T22:46:04&#43;09:00">
    
    <meta property="article:modified_time" content="2020-07-14T22:46:04&#43;09:00">
  

  


    






  




<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "/post/logi/"
  },
  "headline": "Logistic回帰の実装",
  
  "datePublished": "2020-07-14T22:46:04+09:00",
  "dateModified": "2020-07-14T22:46:04+09:00",
  
  "author": {
    "@type": "Person",
    "name": "Kumakt"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "Kumakt Memorandum",
    "logo": {
      "@type": "ImageObject",
      "url": "/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_192x192_fill_lanczos_center_2.png"
    }
  },
  "description": "Logistic回帰の実装について簡単に"
}
</script>

  

  


  


  





  <title>Logistic回帰の実装 | Kumakt Memorandum</title>

</head>
<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search" class="form-control">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  









<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="../../">Kumakt Memorandum</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="../../">Kumakt Memorandum</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-start" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="../../#home"><span>Home</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="../../#posts"><span>Posts</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      
      <li class="nav-item">
        <a class="nav-link js-search" href="#" aria-label="Search"><i class="fas fa-search" aria-hidden="true"></i></a>
      </li>
      

      
      <li class="nav-item dropdown theme-dropdown">
        <a href="#" class="nav-link js-theme-selector" data-toggle="dropdown" aria-haspopup="true">
          <i class="fas fa-palette" aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu">
          <a href="#" class="dropdown-item js-set-theme-light">
            <span>Light</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-dark">
            <span>Dark</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-auto">
            <span>Automatic</span>
          </a>
        </div>
      </li>
      

      

    </ul>

  </div>
</nav>


  <article class="article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1>Logistic回帰の実装</h1>

  

  
    


<div class="article-metadata">

  
  
  
  
  <div>
    

  
  <span ><a href="../../author/kumakt/">Kumakt</a></span>
  </div>
  
  

  
  <span class="article-date">
    
    
      
    
    Jul 14, 2020
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    4 min read
  </span>
  

  
  
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder mr-1"></i><a href="../../category/r/">R</a></span>
  

</div>

    














  
</div>



  <div class="article-container">

    <div class="article-style">
      


<div id="パッケージの読み込み" class="section level3">
<h3>パッケージの読み込み</h3>
<p>今回はパッケージに付属のデータを用いる。</p>
<pre class="r"><code># 必要なパッケージの読み込み
library(ggplot2)
library(dplyr)
library(ggfortify)
library(DAAG)</code></pre>
</div>
<div id="データの確認" class="section level3">
<h3>データの確認</h3>
<pre class="r"><code># データの確認
data(&quot;head.injury&quot;)
summary(head.injury)</code></pre>
<pre><code>##      age.65      amnesia.before   basal.skull.fracture  GCS.decrease    
##  Min.   :0.000   Min.   :0.0000   Min.   :0.00000      Min.   :0.00000  
##  1st Qu.:0.000   1st Qu.:0.0000   1st Qu.:0.00000      1st Qu.:0.00000  
##  Median :0.000   Median :0.0000   Median :0.00000      Median :0.00000  
##  Mean   :0.116   Mean   :0.2047   Mean   :0.06985      Mean   :0.02275  
##  3rd Qu.:0.000   3rd Qu.:0.0000   3rd Qu.:0.00000      3rd Qu.:0.00000  
##  Max.   :1.000   Max.   :1.0000   Max.   :1.00000      Max.   :1.00000  
##      GCS.13        GCS.15.2hours      high.risk      loss.of.consciousness
##  Min.   :0.00000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000       
##  1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000       
##  Median :0.00000   Median :0.0000   Median :0.0000   Median :0.0000       
##  Mean   :0.03749   Mean   :0.1266   Mean   :0.2429   Mean   :0.1118       
##  3rd Qu.:0.00000   3rd Qu.:0.0000   3rd Qu.:0.0000   3rd Qu.:0.0000       
##  Max.   :1.00000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000       
##  open.skull.fracture    vomiting       clinically.important.brain.injury
##  Min.   :0.00000     Min.   :0.00000   Min.   :0.0000                   
##  1st Qu.:0.00000     1st Qu.:0.00000   1st Qu.:0.0000                   
##  Median :0.00000     Median :0.00000   Median :0.0000                   
##  Mean   :0.03685     Mean   :0.09869   Mean   :0.0801                   
##  3rd Qu.:0.00000     3rd Qu.:0.00000   3rd Qu.:0.0000                   
##  Max.   :1.00000     Max.   :1.00000   Max.   :1.0000</code></pre>
<pre class="r"><code>str(head.injury)</code></pre>
<pre><code>## &#39;data.frame&#39;:    3121 obs. of  11 variables:
##  $ age.65                           : num  0 0 0 0 0 0 0 0 1 0 ...
##  $ amnesia.before                   : num  1 0 0 0 0 1 0 0 0 1 ...
##  $ basal.skull.fracture             : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ GCS.decrease                     : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ GCS.13                           : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ GCS.15.2hours                    : num  0 0 0 1 1 0 0 0 0 0 ...
##  $ high.risk                        : num  0 0 0 0 0 0 0 0 1 0 ...
##  $ loss.of.consciousness            : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ open.skull.fracture              : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ vomiting                         : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ clinically.important.brain.injury: num  0 0 0 0 0 0 0 0 0 0 ...</code></pre>
<pre class="r"><code>## 分布や欠損、各変数の型を確認しておく</code></pre>
<ul>
<li>DAAGパッケージに付属のデータセット</li>
</ul>
<p>軽度の頭部外傷のデータセット</p>
<ul>
<li>3121名、11列をもつ。</li>
</ul>
<p>以下、変数名</p>
<ul>
<li><p>age.65：0 = under 65, 1 = over 65</p></li>
<li><p>amnesia.before : 受傷前についての健忘(記憶があるか)
amnesia before impact (less than 30 minutes = 0, more than 30 minutes =1).</p></li>
<li><p>basal.skull.fracture : 頭蓋亭骨折(0 = no fracture, 1 = fracture).</p></li>
<li><p>GCS.decrease : 意識レベル低下
Glasgow Coma Scale decrease (0 = no deterioration, 1 = deterioration).</p></li>
<li><p>GCS.13 : 最初の意識レベル initial Glasgow Coma Scale (0 = not ‘13’, 1 = ‘13’).</p></li>
<li><p>GCS.15.2hours : けがをして2時間後の意識レベル
Glasgow Coma Scale after 2 hours (0 = not ‘15’, 1 = ‘15’).</p></li>
<li><p>high.risk : 神経学的な介入が必要かどうか医師による判断
assessed by clinician as high risk for neurological intervention (0 = not high risk, 1 = high risk).</p></li>
<li><p>loss.of.consciousness : 意識消失の有無(0 = conscious, 1 = loss of consciousness).</p></li>
<li><p>open.skull.fracture : 開放性頭蓋骨骨折(0 = no fracture, 1 = fracture)</p></li>
<li><p>vomiting : 嘔吐の有無(0 = no vomiting, 1 = vomiting)</p></li>
<li><p>clinically.important.brain.injury : CTで臨床的に重要な急性期の脳所見があるかどうか
any acute brain finding revealed on CT (0 = not present, 1 = present).</p></li>
</ul>
<p><References></p>
<p>Stiell, I.G., Wells, G.A., Vandemheen, K., Clement, C., Lesiuk, H., Laupacis, A., McKnight, R.D., Verbee, R., Brison, R., Cass, D., Eisenhauer, M., Greenberg, G.H., and Worthington, J. (2001) The Canadian CT Head Rule for Patients with Minor Head Injury, The Lancet. 357: 1391-1396.</p>
<p>＜今回のモデル＞</p>
<p>目的変数：CT所見に何か異常があるか</p>
<p>興味のある説明変数：健忘の有無</p>
<p>として多変量ロジスティック回帰モデルを作成する。</p>
</div>
<div id="モデルの作成" class="section level3">
<h3>モデルの作成</h3>
<pre class="r"><code># モデルの作成
# glm関数は一般化線形モデルに用いる関数で、familyで自分が使いたい分布を指定する。
#今回は二値変数がアウトカムなので二項分布に従い、リンク関数はlogitなので以下のようになる

model &lt;- glm(clinically.important.brain.injury ~ amnesia.before  + age.65 + GCS.decrease + GCS.15.2hours + GCS.13 + high.risk + loss.of.consciousness + vomiting,family = binomial(link = &quot;logit&quot;),data = head.injury)</code></pre>
</div>
<div id="結果の確認" class="section level3">
<h3>結果の確認</h3>
<pre class="r"><code># モデルの結果確認
summary(model)</code></pre>
<pre><code>## 
## Call:
## glm(formula = clinically.important.brain.injury ~ amnesia.before + 
##     age.65 + GCS.decrease + GCS.15.2hours + GCS.13 + high.risk + 
##     loss.of.consciousness + vomiting, family = binomial(link = &quot;logit&quot;), 
##     data = head.injury)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.6149  -0.3355  -0.2339  -0.1734   2.9001  
## 
## Coefficients:
##                       Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)            -4.1904     0.1485 -28.211  &lt; 2e-16 ***
## amnesia.before          0.6055     0.1656   3.656 0.000256 ***
## age.65                  1.3412     0.1761   7.617 2.60e-14 ***
## GCS.decrease            0.3901     0.3573   1.092 0.274954    
## GCS.15.2hours           1.9435     0.1598  12.164  &lt; 2e-16 ***
## GCS.13                  1.2985     0.2663   4.876 1.09e-06 ***
## high.risk               1.1237     0.1527   7.360 1.84e-13 ***
## loss.of.consciousness   0.8733     0.1926   4.534 5.78e-06 ***
## vomiting                1.2541     0.1865   6.724 1.77e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1741.6  on 3120  degrees of freedom
## Residual deviance: 1287.0  on 3112  degrees of freedom
## AIC: 1305
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>各変数の係数を確認する。</p>
<p>値をオッズ比へ変換する。</p>
<pre class="r"><code># オッズ比と95%信頼区間の確認
result_odds &lt;- as.data.frame(cbind(exp(summary(model)$coefficient[,1]),exp(confint(model))
                                    ,summary(model)$coefficient[,4]))</code></pre>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre class="r"><code># result_oddsというデータフレームの列名を名付ける
names(result_odds) &lt;- c(&quot;Odds ratio&quot;,&quot;lower 95%CI&quot;,&quot;upper 95%CI&quot;,&quot;P value&quot;)
# 小数点２桁で結果を表示
round(result_odds,2)</code></pre>
<pre><code>##                       Odds ratio lower 95%CI upper 95%CI P value
## (Intercept)                 0.02        0.01        0.02    0.00
## amnesia.before              1.83        1.32        2.53    0.00
## age.65                      3.82        2.70        5.39    0.00
## GCS.decrease                1.48        0.71        2.91    0.27
## GCS.15.2hours               6.98        5.10        9.56    0.00
## GCS.13                      3.66        2.15        6.12    0.00
## high.risk                   3.08        2.28        4.15    0.00
## loss.of.consciousness       2.39        1.63        3.47    0.00
## vomiting                    3.50        2.42        5.03    0.00</code></pre>
</div>
<div id="モデルの評価" class="section level3">
<h3>モデルの評価</h3>
<pre class="r"><code>library(pROC)</code></pre>
<pre><code>## Type &#39;citation(&quot;pROC&quot;)&#39; for a citation.</code></pre>
<pre><code>## 
##  次のパッケージを付け加えます: &#39;pROC&#39;</code></pre>
<pre><code>##  以下のオブジェクトは &#39;package:stats&#39; からマスクされています: 
## 
##      cov, smooth, var</code></pre>
<pre class="r"><code>ROC &lt;- roc(response=head.injury$clinically.important.brain.injury, predictor=model$fitted.values)</code></pre>
<pre><code>## Setting levels: control = 0, case = 1</code></pre>
<pre><code>## Setting direction: controls &lt; cases</code></pre>
<pre class="r"><code>ROC</code></pre>
<pre><code>## 
## Call:
## roc.default(response = head.injury$clinically.important.brain.injury,     predictor = model$fitted.values)
## 
## Data: model$fitted.values in 2871 controls (head.injury$clinically.important.brain.injury 0) &lt; 250 cases (head.injury$clinically.important.brain.injury 1).
## Area under the curve: 0.8387</code></pre>
<pre class="r"><code>plot(ROC)</code></pre>
<p><img src="../../post/logi_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>ROC(C統計量)は0.837くらいで今回のモデルの当てはまりはよさそうである。</p>
<p>「怪我の前の記憶喪失(健忘)」と「CT所見に何かしら異常が見つかるか」の関係をみることが今回の目的であり、<br>
最終結果はオッズ比 1.83, 95%CI 1.32 - 2.53となり、受傷時の健忘はCTの異常所見の発見に影響があると言える。</p>
</div>

    </div>

    






<div class="article-tags">
  
  <a class="badge badge-light" href="../../tag/glm/">GLM</a>
  
</div>



<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=../../post/logi/&amp;text=Logistic%e5%9b%9e%e5%b8%b0%e3%81%ae%e5%ae%9f%e8%a3%85" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=/post/logi/&amp;t=Logistic%e5%9b%9e%e5%b8%b0%e3%81%ae%e5%ae%9f%e8%a3%85" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Logistic%e5%9b%9e%e5%b8%b0%e3%81%ae%e5%ae%9f%e8%a3%85&amp;body=/post/logi/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=../../post/logi/&amp;title=Logistic%e5%9b%9e%e5%b8%b0%e3%81%ae%e5%ae%9f%e8%a3%85" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="whatsapp://send?text=Logistic%e5%9b%9e%e5%b8%b0%e3%81%ae%e5%ae%9f%e8%a3%85%20/post/logi/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=../../post/logi/&amp;title=Logistic%e5%9b%9e%e5%b8%b0%e3%81%ae%e5%ae%9f%e8%a3%85" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>












  
    
    





  


  












  
  
  <div class="article-widget content-widget-hr">
    <h3>Related</h3>
    <ul>
      
      <li><a href="../../post/propensity_score_multi/">Rによる傾向スコア分析の実装２</a></li>
      
      <li><a href="../../post/multilevel/">Rによるマルチレベル分析の実装</a></li>
      
      <li><a href="../../post/propensity_score/">Rによる傾向スコアの実装</a></li>
      
      <li><a href="../../post/survival/">Rによる生存時間解析の実装</a></li>
      
      <li><a href="../../post/linear/">線形回帰モデルの基礎</a></li>
      
    </ul>
  </div>
  





  </div>
</article>

      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js" integrity="sha256-eOgo0OtLL4cdq7RdwRUiGKLX9XsIJ7nGhWEKbohmVAQ=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/r.min.js"></script>
        
      

    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.js" integrity="sha256-EErZamuLefUnbMBQbsEqu1USa+btR2oIlCpBJbyD4/g=" crossorigin="anonymous"></script>
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    <script>const isSiteThemeDark = false;</script>
    

    
    
    
    
    
    
    <script>
      const search_config = {"indexURI":"/index.json","minLength":1,"threshold":0.3};
      const i18n = {"no_results":"No results found","placeholder":"Search...","results":"results found"};
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks",
        'slides' : "Slides"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="../../js/academic.min.66c553246b0f279a03be6e5597f72b52.js"></script>

    






  
  
  <div class="container">
    <footer class="site-footer">
  
  <p class="powered-by">
    
      <a href="../../privacy/">Privacy Policy</a>
    
    
       &middot; 
      <a href="../../terms/">Terms</a>
    
  </p>
  

  <p class="powered-by">
    
  </p>

  
  






  <p class="powered-by">
    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" class="back-to-top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
